<?php

########################################################################
# Extension Manager/Repository config file for ext: "apn_frontend"
#
# Auto generated by Extension Builder 2012-12-11
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Command line kickstarter',
	'description' => '',
	'category' => 'misc',
	'author' => 'Ameos',
	'author_email' => 'typo3dev@ameos.com',
	'author_company' => 'Ameos',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
